### ISSUE TITLE
Error: Cannot read property 'split' of undefined on fullQuery request

### ISSUE THREAD

**Issue by T1MOXA** [mathhulk/minecraft-status#2]
```js
const { MinecraftQuery } = require("minecraft-status");
MinecraftQuery.fullQuery('localhost', 25565, console.log);
```

```
\node_modules\minecraft-status\src\MinecraftQuery.class.js:119
                                serverModification[1].split("; ").forEach( (value) => {
                                                      ^

TypeError: Cannot read property 'split' of undefined
    at Socket.<anonymous> (\node_modules\minecraft-status\src\MinecraftQuery.class.js:119:27)
    at Socket.emit (events.js:321:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
```

**Comment by mathhulk** [comment]
Hello. I will look into this today! I apologize for the delay.

**Comment by mathhulk** [comment]
Should be fixed in the latest update. 

I had not accounted for the absence of modifications in the response and thus an error would appear for vanilla Minecraft servers and servers without plugins.

Thanks!
